### ISSUE TITLE
Crash when adding timer when AT is also in the process of adding one

### ISSUE THREAD

**Issue by RobvanderDoes** [OpenViX/enigma2#278]
Reproduce:
1- Add an AT. Make sure it's a 'complicated' one, so the process takes some time.
A complicated AT has e.g. wide parameters (not identical, no specific time frame, no specific day, no specific channel.
2- Add manually a timer.

Result:
When the two processes are indeed happening at the same time (which does happen in real life) E2 crashes (see attached log).

 
[Enigma2_crash_2018-07-26_17-48-39.zip](https://github.com/OpenViX/enigma2/files/2236475/Enigma2_crash_2018-07-26_17-48-39.zip)

**Comment by Huevos** [comment]
Looks like some sort of lock is needed so timer is only processed if you have 100% control over that file.

**Comment by RobvanderDoes** [comment]
I have absolutely no idea how to fix that, but a crash is never a good response to a normal use case.

**Comment by original-birdman** [comment]
Can be fixed using:

https://docs.python.org/2/library/mutex.html

**Comment by RobvanderDoes** [comment]
A fix would be very much appreciated.

**Comment by original-birdman** [comment]
I have an idea (which was why i commented).

The assumptions would be that the two (or more) threads involved in a concurrent update could both(all) put up with pausing for a second before continuing.
I _believe_ that recordings run in their own threads and aren't involved with anything other than running the broadcast stream to file, so play no part here.

**Comment by original-birdman** [comment]
I have some code, but wont; be abel to even stat testing it until Tuesday:

This is the diff, if anyone else feels brave/foolhardy:
```
--- RecordTimer.py.orig 2018-12-14 16:47:12.053097336 +0000
+++ RecordTimer.py      2018-12-14 12:49:28.584279627 +0000
@@ -20,7 +20,7 @@
 import NavigationInstance
 from ServiceReference import ServiceReference
 
-from time import localtime, strftime, ctime, time
+from time import localtime, strftime, ctime, time, sleep
 from bisect import insort
 from sys import maxint
 
@@ -1084,6 +1084,21 @@
 
                list.append('</timers>\n')
 
+# Need to ensure there is only one thread updating this at any one time!
+# So open the target file and get a(n advisory) write lock on it.
+#
+               import fcntl
+               tfile = open(self.Filename, "w+")
+               while True:
+                       try:
+                               fcntl.flock(tfile, fcntl.LOCK_EX | fcntl.LOCK_NB)
+                               break
+                       except IOError as e:
+                               if e.errno != errno.EAGAIN:
+                                       raise   # any unrelated IOErrors
+                       else:
+                               sleep(0.1)
+
                file = open(self.Filename + ".writing", "w")
                for x in list:
                        file.write(x)
@@ -1092,6 +1107,7 @@
                os.fsync(file.fileno())
                file.close()
                os.rename(self.Filename + ".writing", self.Filename)
+               tfile.close()   # Release the lock
 
        def getNextZapTime(self):
                now = time()
```

**Comment by original-birdman** [comment]
Hmmmm...as is often the case writing code to handle one case highlights another.

If a manual timer edit/change (or an AutoTimer run) is changing the timers we need to ensure that RecordTimer (which really only changes the status) doesn't wipe out the change (or _v.v._).
So there might need to be a lock on updating the timer list (which is in memory) rather than a lock on writing this out.

**Comment by RobvanderDoes** [comment]
Is there any chance to have a proper look into this?

**Comment by original-birdman** [comment]
Delayed by other things...
My first look through indicated that there may be more of a problem (concurrent updates) but it then transpired that Python threads aren't actual threads so it's probably not as bad/complicateed as it might have been.

**Comment by original-birdman** [comment]
Ah, it's coming back to me now.
There appeared to be various other places that needed protecting (including bits of the AutoTimer code, which isn't Vix-specific), but I've since found out that Python threads aren't actually concurrent threads, so I _think_ that this problem goes away.
Apart from the one you see here.
So I just need to put a protecting semaphore in the `saveTimer()` code.

**Comment by original-birdman** [comment]
I've managed to reproduce the error by adding a 5s sleep before the rename.
I also now have a fix (although the thrill of adding all timers for "Coronation Street" an all channels at all times is still running because of that 5s wait).

I'll start a thread in the Vix developers forum noting what I've done (which is actually not a lot...).

**Comment by original-birdman** [comment]
https://github.com/OpenViX/enigma2/pull/371

**Comment by RobvanderDoes** [comment]
As far as I tested now this fixes the issue.
Closed as fixed.
Thanks a lot.
