### ISSUE TITLE
Teletext subtitle timings on playback

### ISSUE THREAD

**Issue by nikolai-the-second** [OpenViX/enigma2#28]
Teletext subtitles work ok on live tv.
On recording playback the timings are wrong, they come in bunches, the first is on time, the rest too early.
Timing settings on subtitle menu don't help.

When watching recording on a pc with vlc player the timings are correct, so timing info is in the file, also it it possible to get them right as vlc can do it.

Dvb subtitles are ok also on playback.

All openvix images at least since jun 2014, vuduo2, Finland.

**Comment by RobvanderDoes** [comment]
You cannot make a general statement like "on recording playback the timings are wrong". I use them on a daily basis, and they are always correct.
This is a very old discussion. When the timing is correct during live-TV, but not during playback of the same show, this is simply a matter of lacking timing info. This is irrespective of any PC-player can correct this or not. Some services take care of issuing proper timestamps, others don't. Nothing can be done about that at the receiver-end.

**Comment by RobvanderDoes** [comment]
And if you really think it's a fault of the ViX-image, you should try and test other images.

**Comment by nikolai-the-second** [comment]
In my box, teletext subtitle timings on recording playback are wrong.
On all channels that put subtitles on teletext only.
Movies are unwatcable.
Dvb subtitles work.

Read my lips : teletext subtitles

Subtitles can be both dvb ot teletext. Only teletext is wrong. 
You surely use dvb texts if they all work, Good for you.

The fault is somewhere in the vix image which is in my box.

Tell me where teletext subtitles are implemented, I will fix them myself if you don't accept it as a bug or don't know how to fix it.

**Comment by RobvanderDoes** [comment]
Since you were reporting about TT-subtitles, I was also referring to them (I never use DVB-subs anyway).
And as they are fine on all the services I use (I use TT-subs on a daily basis on all Dutch, Belgian, French, German and English services) this proves that if the timestamps are OK, the display of the subs is fine.
Of course if the timestamps are lacking, or not consistent, there is no way to display them on the correct time. The fact that they are being displayed correctly on live-TV, as you reported, is due to the fact that they will be displayed the very moment they are received. During playback there is no such mechanism.
Sometimes timestamps are consistent-not-OK; in that case the ViX-image allows for a (positive or negative) delay, that will 'fix' the timely display.

And I repeat: if you're really convinced this to be an issue with ViX (which is not the case) you really should try a(ny) other image. That seems to be the only way to convince you about this issue.

**Comment by nikolai-the-second** [comment]
If there is no such mechanism that you describe during playback, how can vlc player show the texts ok when the same recording is streamed to a pc? The box cannot. Therefore there is a bug in the box.

Viasat film on dvb-t in Finland definitely does not work. I'm not the only one with this problem.

It appears as if there is no text end time on stream, an earlier version of vlc showed one text until the next one was to be shown. But the start times were ok even then.

I have no way of knowing if this is a vix image problem, not knowing where in in the system subtitles are handled.

**Comment by RobvanderDoes** [comment]
Yes you have: test other images as I suggested twice. then you can test using the same services as you used on ViX. This will clearly show you this is not image-related.

**Comment by nikolai-the-second** [comment]
I know these boxes are for nerds, but I'm not nerd enough to start testing images. This box for us is a household item.

Do you know for sure that different images have their own subtitle handlers? Or is there a common component somewhere? Do you (or anyone) know where, in code, subtitles are handled?
