### ISSUE TITLE
Signal Characteristics

### ISSUE THREAD

**Issue by EMJB** [OpenViX/enigma2#398]
Further to the discussion in issue 355, I attach the results of looking more closely at the reporting of signal characteristics in OpenVix. I have tried to suggest some improvements, but some of the problems (notably what I find to be confusing terminology) seem to require a very broad consensus before any corrective action can be started.
[SIGNAL CHARACTERISTICS V1.docx](https://github.com/OpenViX/enigma2/files/2977681/SIGNAL.CHARACTERISTICS.V1.docx)

 

Comments please.

**Comment by EMJB** [comment]
Has no one any opinions on what I wrote???

**Comment by Huevos** [comment]
"The aim of this document is to provoke discussions"

Looks like that bit wasn't successful.

**Comment by EMJB** [comment]
I am rather dissappointed that no-one has any comments, either positive or negative.

As a final effort to improve matters, I make the following suggestion:

(a) A new function (traceFrontendData?) is added to frontend.cpp with the same arguments as readFrontendData, and which returns a string containing:
	(i) The results of calls to both old and new APIs, 
	(ii) The result that an equivalent readFrontendData call
	(iii) An assessment of the confidence in that data. 
For example where the driver failed to respond to a relevant API call, the confidence would be reported as zero -t present readFrontendData returns value of zero which is often a valid value. 

(b) SatFinder (Signal Finder in the menu) is amended to allow the user to display and optionally record the output of the new function. This would then allow data on different tuners to be collected in sufficient detail to identify where any improvements need to be made to driver or readFrontendData.

(c) Any plugin etc using data derived from readFrontendData could run "traceFrontendData" once and parse the results to extract the confidence level and hence determine whether that data is meaningful, possibly hiding it's display for example.

I would be happy to expand on my ideas for, and then implement, (a) & (b), but only if there is a general agreement that this is the correct way forward - I don't want to do all the hard work and then have the changes rejected!

**Comment by AbuBaniaz** [comment]
I read your article twice, I did not get the point/s you were trying to make. Too much extraneous text or text with no purpose. If you are going to expand on your ideas, please get to the point. We are here to improve E2, not write/read novels.

Why do we need a new function? Surely if the existing functions are giving wrong data, we should correct them so they give the correct data? If this is not possible, then by all means create a new function. Not sure about `trace` though.

To me, it is correct that if a device does not use/respond to new API, it resorts to using the old API. Otherwise you have to have a register of which device uses new/old api or find some other way to establish this.

I wouldn't touch plugins/applets until you get correct data.

Good luck with getting drivers changed.

**Comment by EMJB** [comment]
@ Abu Baniaz:

Clearly you have not understood some of the points I have been trying to make on more than one occasion, and in particular:

(1) The terminology used is very confusing, with signal names changing for no obvious reason. Equating AGC level to relative signal strength is an extreme example. Without understanding what the data types are meant to represent how can anybody sensibly decide whether they are correct, or decide which is best for purposes such as signal comparison  in ABM frequency Finder? I therefore tried to explain my understanding of each data type, and what limits that implies on the data.

(2) The current logging is inadequate to identify whether any problems are in the driver or in the readFrontendData processing, so some action is needed to be able to identify driver problems. Hence something needs to be done in if one is to collect the evidence needed to make any changes.

(3) The chances of getting many drivers changed seems negligible, and there are precedents for corrections to be incorporated in readFrontendData. Without understanding what data the driver is producing, it is difficult to see how one could propose such corrections.

(4) readFrontendData returns zero when no data is available. Sometimes the difference between this and a true value of zero is self-evident, but it is very important but not obvious in the case of Bit Error Ratio.

(5) Reversion to the old API is fine if it works and produces the same information as the new API, but the signal quality and BER measures appear to be significantly different. Furthermore it appears that tuner-specific code necessary for the old API is needed but missing for recent tuners.

I was able to make changes to readFrontendData to fix the problems for **MY** tuners by making a new version of frontend.cpp with additional logging to find out what was happening. I would like to make a contribution towards fixing the problems that exist in this area, but can see no other way of doing so. 

EMJB

**Comment by AbuBaniaz** [comment]
Then please make the required changes. 

As before, the offer to build test images with your changes still stands. Should you wish to do so, please upload the modified files.

**Comment by IanSav** [comment]
I didn't review your proposals as I don't know you and hence will not access external Microsoft documents (where viruses may linger) that you supplied.

Do you have a plain text version of your proposal?

**Comment by EMJB** [comment]
@IanSav:

Plain text version attached, but it will be more difficult to follow as tables etc do not line up and I think footnotes get lost.

[SIGNAL CHARACTERISTICS V1.txt](https://github.com/OpenViX/enigma2/files/3178934/SIGNAL.CHARACTERISTICS.V1.txt)

**Comment by IanSav** [comment]
If you wish to preserve formatting you could always try RTF format.  It can't contain marcos so should be safe for distribution.

**Comment by EMJB** [comment]
@Abu Baniaz:

I would prefer to get agreement as to the need for, and scope of, any changes before potentially wasting everyone's time with test builds.

EMJB

**Comment by EMJB** [comment]
@IanSav 
Good point about rtf - not a format I normally use. This site will not accept rtf on its own, but I have included it in the attached zip file

[Signal Characteristics V1.zip](https://github.com/OpenViX/enigma2/files/3179020/Signal.Characteristics.V1.zip)

.

**Comment by EMJB** [comment]
@ Abu Baniaz:

You wrote " I did not get the point/s you were trying to make." - I am sorry you did not understand the introductory section. Perhaps I should have been rather more detailed and said something like:

"Multiple names are used for the same data within OpenVix, in at one case totally misleading and rarely sufficiently detailed to avoid potential misunderstandings - I have not found any documentation to clarify these and code comments are so sparse as to give little help. The data available at the DVB API is not always well defined, and is not all implemented by all drivers (which may also have bugs!). To tidy up this area it seems to me that we need:

(a) An understanding of the uses for the data, so that their ideal characteristics can be established. In my opinion, this requires some understanding of the DVB system, and I have spelt out **my** (possibly flawed) understanding of both the system and ideal data and its use. 
 
(b) More information is required as to the behaviour of the many tuners in use so that changes to frontend.cpp can be made (if necessary) to get as near to the ideal as possible."

**Comment by AbuBaniaz** [comment]
Thank you for your comment. I will not be following this topic.

I wish you well in your endeavours

**Comment by IanSav** [comment]
Your alternative introduction should be added to your document as it presents your case in a significantly more clear way.

My Enigma2 interests are directed more towards the user interface and usability.  That said I am still digesting your document but I wanted to offer some immediate feedback and to indicate I am still here.

To be truly useful any proposals and designs should try to include all major Enigma2 images.  Don't just focus on OpenViX.

The document, in particular section 3, is very technical.  I am not sure it is helping you to sell your proposals.  Perhaps it could be moved to an appendix so as to not put a less technical reader off the core intent of the proposal.

You make an interesting point about issues swapping between old and new APIs.  Unfortunately I think you may be biting off far too much in a single chomp.  I believe it could be productive to first identify all points in the existing code where the underlying drivers and frontend API are being used.  Next I would be removing any "magic" numbers and replacing them with meaningful variable names.  Next I would be identifying the appropriate opportunity of where to concentrate the most logical interface between the lower level drivers and Enigma2.  Once the improvement opportunities are identified then a change case proposal can be formulated.

I would also advise caution in expecting lower level drivers and code to be changeable.  In many, if not all cases, this code only exists as binary objects for which source code is not available.  Others with closer access to the hardware developers may have more information about the likelihood of changes being made to these parts of the code.

I have not examined any of the code in the areas you are discussing.  I would hope that the Python code can be cleaned up so that all the Python layer code can cleanly point to a unified C++ layer interface that can then be appropriately adjusted to fit the underlying APIs.  All the Python layer code MUST not use magic numbers but appropriately names variables.  My intended aim would be to minimise the surface area of interaction between the components.  Ideally the Python layer code should require no or minimal level of change to support new hardware.

For example, from my current understanding of the system and your proposal it would appear that all the Python code should be cleaned up to directly interface with the Enigma2 C++ layer interface in a clean, organised and uniform manner.  The C++ code should then interface with the underlying drivers and system API code.  As much as possible the Python layer code should have no knowledge or need for knowledge of the underlying drivers and system APIs.  This should then allow the single C++ code component of Enigma2 to handle the differing driver and API interfaces.

The other aspect of the tuner interface that appears to be missing from your proposal is that the Python / UI tuner status screens appear to be unable to extract the *current* tuning parameters from the tuner.  (If you don't understand what I mean please ask.)

Section 5 of the document is very technical.  I am finding it difficult to comprehend.  Perhaps later in the process the issues and scope may reduce to a point where the details you provide will become easier to follow.

I hope my comments don't come across as telling you stuff that you already know.  They are my take on I believe you are proposing.  I think the next step should be for you to review all the code and propose the sort of changes you think should be made.

**Comment by EMJB** [comment]
@ianSav:

Thanks for taking the trouble to reply in a positive way. Clearly some re-organisation of the document would be helpful - I was obviously in too much of a hurry to get it out and it is laid out more to reflect the history of my investigations etc than to match the interests of particular groups. I will aim for a new version in a week's time. In terms of some of your comments:

(1) I understand that frontend.cpp is intended to provide the cpp/Python interface to which your refer.

(2) I would heartily endorse the need to look wider than OpenVix,. I understand that until recently frontend.cpp was maintained by a common team, but that the team has been disbanded. As a newcomer to Enigma2, I do not have any understanding how to get the a common approach, nor any contacts in other image teams.

(3) At the moment I do not understand what the code should be trying to do, so I consider talk of reviewing code changes to fix problems to be premature.

(4) I think I understand you reference to extracting the current tuner parameters, which I take to be things like frequency, bandwidth, inversion etc. - I hit this point recently but it was not important enough to have spent much time on it.

EMJB

**Comment by IanSav** [comment]
I wouldn't invest too much time massively reworking your discussion paper.  Try to demonstrate the types of changes to the code you believe are warranted.

1) Agreed, but is it still serving the needs of a more modern Enigma2 and the drivers offered by various manufacturers?

2) For OpenATV contact Captain.  For OpenViX contact WanWizard.  (Littlesat is a more technical contact within OpenPLi but he has medical issues that make it a little difficult to communicate with him.)

3) When you better define the problem and formulate a solution you may find more interest in the issue.

4) Unfortunately this is the aspect of your investigation that most interests me as this directly affects the usability of the user interface.  ;)

**Comment by RobvanderDoes** [comment]
WanWizard is a PLi-member, not ViX.

**Comment by IanSav** [comment]
Thank you for the correction.  Original post updated.

**Comment by Tony-il-Capo** [comment]
In the end, too much work for a little cosmetic reward...

But this issue depends heavily on (closed) drivers/hardware, nothing really we can do about that.

Good hardware and drivers have currently no problem with this.

**Comment by IanSav** [comment]
There are aspects of this proposal that I think are still worth pursuing.

The closed drivers are an issue.  If a consistent API that can support all images is defined and created there could be a chance for drivers to be updated to comply.  This is unlikely to succeed if there is ANY disagreement between the various images.

**Comment by EMJB** [comment]
I think it is easy to overemphasise the issue of drivers being closed. To my mind to meet the spirit of open source software, the code needs to be supported by precise definitions of its inputs and outputs, together with justifications for conversion factors etc. As Tony hinted, the definitions of inputs from the hardware seem to be rarely available, so any changes risk fixing one problem and generating another, and the prospect of implementing missing functionality (e.g. BER reports) seem negligible.

Tony makes the point "Good hardware and drivers have currently no problem with this". I would be interested to know what his criteria are - Does this exclude drivers that do not support both new API BER figures, for example? If images are not to handle other drivers gracefully, surely some effort needs to be made to warn potential users of the associated tuners.

Also as IanSav has pointed out many of the issues are unrelated to drivers such as misleading naming. How can one possibly justify labelling signal strength data on the PVR User's display as AGC, for example?

**Comment by Huevos** [comment]
@EMJB, if what cones out of the drivers is "junk" or "nothing" do you really want us to waste time trying to implement a band-aid code fix around this?

**Comment by EMJB** [comment]
@ Huevos: we had this discussion last autum when I proposed some changes to Frequency Finder which you rejected with the same emotive terminology. The simple answer to your question is that if what comes out of the drivers is "junk" or "nothing" I do think there should a "band-aid code fix around this", particularly where it leaves the PVR User up in the air with no idea of what is going wrong, and even more particularly when he/she could sensibly be advised of avoidance action such to use an alternative tuner. If you do not wish to use your time for such an activity, my offer to do so made last autumn still stands.

I assume you are referring o the sort of changes I have suggested to Frequency Finder, or do you also believe the PVR User should not be advised when dsiplayed data is not valid?

Clearly behind this is a major philosophical issue, centred round the intended user-friendliness of OpenVix. I would like to take every opportunity to proactively help users as much as possible when problems (are likely to) occur, whereas you seem happy to let users get into trouble and rely on the forums for help. I do not understand who makes this sort of decision on OpenVix strategy, but I do believe an OpenVix strategy needs to be defined so we can gradually move towards it.

I will try to make sure version 2 of my note (which has been somewhat delayed - sorry) identifies these issues in a way that can be appreciated by those unfamiliar with the details of the driver and data content issues.

**Comment by Huevos** [comment]
Instead of writing "notes" why don't you spend the time writing an algorithm. Start with boxes like Vu+ Ultimo 4K that don't have an SNR dB algo.

**Comment by EMJB** [comment]
@Huevos:
Because:
  (1) I am not 100% convinced I know exactly what the legacy API is trying to do
  (2) I do not have the hardware you mention, to even collect such basic data as the scaling & any offset in the legacy snrValue data.
  (3) I lack the theoretical knowledge or access to the hardware details to decide whether corrections for things like QAM type are needed for that tuner.
  (4) I think the use of the legacy data should be avoided wherever the new data is available, so updating the legacy logic does not seem fruitful (or are you saying they do not provide the new API data?).

Perhaps another philosophical difference between us is I like to understand the data I am trying to process and the data I am trying to generate before I contemplate algorithms and code.

**Comment by Huevos** [comment]
Is that a joke? Are you saying I don't understand what I am doing?

**Comment by EMJB** [comment]
When you suggest I spend my time: 

(a) Writing an algorithm to convert from something I have no means of getting a sensible specification to something that is ill defined 

rather than:

(b) Making suggestions as to how logging could be implemented to get some information on that input data, and what the definition of the output should be.

it is difficult to draw any other conclusion.  As to you knowing what you are doing, as far as I can see you are not doing anything in this area, and a major point I wanted to get across is that I am not sure anyone currently involved knows what the various data items mean, and I believe that they are almost certainly being misused.

I appreciate you do not agree with some of the points I was trying to make in version 1. Hopefully the changes I am making in version 2 will separate the key issues, to enable sensible discussion of more aspects without a detailed DVB/Hardware knowledge. Please wait a few days till I can get that out and make your comments against those suggestions.

**Comment by Huevos** [comment]
The enigma community small and thinly spread across several images. Don't expect anyone to be interested in your project or to help. If they do that is a bonus but most of my enigma projects I end up doing alone. If a project is interesting a couple of people might appear out of the woodwork on the home stretch, but not much more. If you start your project by asking people to read long intricate texts of specifications and terminology or dictionaries it will be doomed from the get-go. If you need so specific help by all means ask, but don't expect people to be exited about fixing some arithmetic to work around some drivers the manufacturers are to lazy to sort out for themselves when there are so many more pressing issues to expend time and effort on.

**Comment by IanSav** [comment]
Let us please stand back and avoid name calling etc on this interesting and potentially important topic.

What EMJB is describing is some ways is starting to sound like OP 41 in the Australian broadcasting standards.  [Free TV Australia Operational Practice OP-41](http://www.freetv.com.au/media/Engineering/Free_TV_OP_41_LCN_Descriptor_Issue_8_July_2016.pdf)

This document essentially describes how the scan process should examine all broadcast signals received and rate them for strength and quality.  The best signal is then assigned to the primary LCN and the weaker options are assigned LCNs in a duplication pool.  Thus when a user selects a service using the published LCN they should be getting the best available version of that service.  For this to work the C++ and Python layers must be able to interrogate the tuner information available from the drivers in a reliable way.

This information would also be helpful in correcting the Tuner Information displays where users currently see entries like "Auto" instead of the live tuner parameters.

Huevos and I tend to dive in and explore a problem and workshop the solution as we go.  It is a sort of iterative development.  I try to document the results once I have found the best approach.  EMJB appears to prefer to research, understand and document the issue fully before commencing work.  Each approach has its values and is usually a personal choice.

The issue for us "tinkerers" is that we process information and proposals better when we can see them in action.  I suspect that much of the Enigma2 community are like this.  That is why your documents have been so difficult for many to digest.  I think you could strengthen your case by starting to cut some sample code that perhaps demonstrates the issues and create a pathway to explaining how you would like to deal with them.  I often create sample or test plugins to do this to explain my change proposals.  Perhaps you could try something similar.

**Comment by IanSav** [comment]
I have been talking to Captain from the OpenATV team about these driver issues.  I have suggested that he also contribute to this discussion so that perhaps we can make inroads to getting an API defined so that all images and teams can make the same requests from all hardware manufacturers for driver operability.  This could be in the best interest for all images and teams and remove driver inconsistencies from the equation.

**Comment by AbuBaniaz** [comment]
Enigma2 code should conform to dvb standards.

The drivers should conform to dvb standards.

We can't do anything about drivers. The more we add hacks to work around shortcomings, the less likely they are to supply correct drivers.

**Comment by IanSav** [comment]
Unfortunately, like many standards, with the DVB-T standards there are lots from which to choose.  Australia, for example, has its own interpretations of DVB-T that differ from elsewhere.  They all stem from ETSI but there are local wrinkles.

This is an issue that causes Huevos constant grief.

**Comment by Huevos** [comment]
No, the DVB standards are standard. What's happened with AUS is your government is imposing stuff that is outside the standard.

**Comment by IanSav** [comment]
@EMJB: Are you still with us?

**Comment by EMJB** [comment]
@ IanSav
Yes, but some of the comments show such a deep misunderstanding of the issues that I feel it is better to concentrate on updating my document than replying in great detail. Looks like a few more days unless some more comments appear.

**Comment by IanSav** [comment]
I believe that Captain is now also monitoring this thread so hopefully we can get some agreement across the images on how to standardise.  Hopefully this will give us an increased influence over the driver creators to address issues within their code.

**Comment by Huevos** [comment]
How can you "standardise" broken drivers?

**Comment by EMJB** [comment]
I have updated my document, with the aim of making it easier to follow for those who do not wish to get involved in the technicalities behind some of the issues, and address more specific points raised here. I am concerned, however, that it makes it too easy for my assumptions etc to not get the critical & expert analysis needed. The zip file contains and rtf version.
[SIGNAL CHARACTERISTICS V2.docx](https://github.com/OpenViX/enigma2/files/3238145/SIGNAL.CHARACTERISTICS.V2.docx)
[Signal Characteristics V2.zip](https://github.com/OpenViX/enigma2/files/3238144/Signal.Characteristics.V2.zip)

**Comment by IanSav** [comment]
Document fetched but it is way too late here (Australia) to read it now.  :)

**Comment by IanSav** [comment]
> How can you "standardise" how to deal with broken drivers?

I felt that if all the images agree on the expectations from the drivers we may be able to get the broken drivers fixed.  Again, this is not my area of expertise so I may be off the mark but I am trying to to be supportive.

**Comment by AbuBaniaz** [comment]
>but these were rejected on a matter of principle rather than detail.
You post such rubbish

Just submit a pull request with the changes you want to make

**Comment by EMJB** [comment]
@ Abu Baniaz:

In my opinion you are grossly over-reacting to a single sentence, which incidentally is still my interpretation of what happened. If I missed something, please point out those details and accept my apologies.

You also seem to have failed to appreciate that in many cases I am a long way from being in a position to generate a pull requests for one or more of the following reasons:

(a) I lack the knowledge, expertise, and/or  confidence to make code changes, and need help.

(b) I am proposing changes that affect all images, so it is particularly important that all concerned buy into the concepts before even contemplating any code.

(c) I certainly don't want to spend time coding something like my suggestions for additional logging, only to find someone has a better idea.

I will be happy to continue the discussions elsewhere if anyone wants to pursue the points I have made.

**Comment by IanSav** [comment]
Unfortunately I have pointed OpenPLi and OpenATV people here.

**Comment by AbuBaniaz** [comment]
Rob, please do not re-open this again. 

We will not be taking any changes from this person.
