### ISSUE TITLE
Provide option to disable geolocation services that run on every boot 

### ISSUE THREAD

**Issue by jksat** [OpenViX/enigma2#544]
**Already posted this in OpenPli section, but since the same code is here too, it also applies.**

As title states, users need means of disabling location check at every boot, this was created by @IanSav  without any regard to end user choice.

This may be a sensitive matter to many and peolple start to question the entire E2 project, ([read comments](https://github.com/openatv/enigma2/issues/1563)) so, should be users that make the final decision of using this services or not.

After all, this 'tool' is only needed by a very few users, it sets for them the timezone, for most there's no need to be running this at every boot.

**Comment by IanSav** [comment]
This matter has already been dealt with on OpenViX.  Once I get confirmation that the code changes are working as intended the changes will be applied to OpenATV and OpenPLi.

See:
https://github.com/OpenViX/enigma2/commit/24a93fe29cd6005f5892ad346c6b758f8dca9d1a
https://github.com/OpenViX/enigma2/commit/65e04e583521f536c5031af8ab5682fa845f0bdf

**Comment by Huevos** [comment]
So you signed up to github just to comment on this? Did you do it of your own accord or did someone encourage you?

**Comment by AbuBaniaz** [comment]
Can someone please post instructions how to disable the crap.

Windows does not try to pinpoint you for setting timezone without your permission. Same for Ubuntu.

The code did not even work.

**Comment by Huevos** [comment]
If you don't want it just remove it from your repo.

**Comment by AbuBaniaz** [comment]
How the fuck do you do that!

**Comment by AbuBaniaz** [comment]
It doesn't work for anyone other that you two!

**Comment by AbuBaniaz** [comment]
If you delete the tracker receiver does not boot.

**Comment by Huevos** [comment]
What do you mean it doesn't work? Please explain.

**Comment by AbuBaniaz** [comment]
Did you not read the forum?

**Comment by Huevos** [comment]
No, I haven't got time. Busy on other things.

**Comment by AbuBaniaz** [comment]
Apart from Ian, everyone is saying this is not required. He is saying you sanctioned this.

When you flash a receiver, what zone does it detect for you?

**Comment by Huevos** [comment]
Right now I am not sure who "he" is or what you are talking about.

**Comment by Huevos** [comment]
> 
> 
> How the fuck do you do that!

Is there any need for that?

**Comment by AbuBaniaz** [comment]
Ian posted that Huevos sanctioned changes in conversation overseen by Stef.

Yet Huevos stated elsewhere he doesn't see need for geolocation file but at same time likes automation.

Huevos also stated he didn't want to discuss it.

**Comment by Huevos** [comment]
> 
> 
> Ian posted that Huevos sanctioned changes in conversation overseen by Stef.
> 
> Yet Huevos stated elsewhere he doesn't see need for geolocation file but at same time likes automation.
> 
> Huevos also stated he didn't want to discuss it.

Please don't post the content of private forums and chats in public areas.

**Comment by AbuBaniaz** [comment]
Who actually is in favour of this geolocation?

Nobody on ViX Team has said this is a good thing.

**Comment by Huevos** [comment]
First Ian is asked to disable it so it does not work on reboot and now you are complaining that it is not working. I really don't understand what you want.

Are you against this because Ian wrote it?

**Comment by AbuBaniaz** [comment]
I am against a device locating me without my consent

**Comment by AbuBaniaz** [comment]
The option he described on forum is to enable subsequent location attempts even after you have set location. That is a part fix. There is no option to disable it completely.

**Comment by Huevos** [comment]
It is just feeding back your own data to yourself.

**Comment by AbuBaniaz** [comment]
It is still locating you.

**Comment by Huevos** [comment]
LOL

**Comment by AbuBaniaz** [comment]
As I said no other system does this without user permission.

**Comment by Huevos** [comment]
And your point is?

**Comment by AbuBaniaz** [comment]
Geolocation service should not run without user enabling it.

**Comment by Huevos** [comment]
The data is just being looped back to the user. Every time an STB does something on the public internet it exposes its IP. That can be used by any website for checking the location of the request.

**Comment by AbuBaniaz** [comment]
We are not talking about what websites do. We are talking about location function.

Yes we are using IP address.

The function of locating users without their permission is new.

**Comment by Huevos** [comment]
The way you describe this is as if something underhand is happening. That is not the case. We are not locating the user. The user STB contacts a website. That website feeds the data straight  back to the user without saving anything. We are not in the loop.

**Comment by AbuBaniaz** [comment]
The receiver is determining position  without permission.

**Comment by Huevos** [comment]
The receiver is doing a database lookup. The requested data is returned straight to the user. Are you suggesting the user may not know their own location and once they find out they may use that information against themselves?

Please explain how this is any different to a receiver contacting something such as a time server.

**Comment by AbuBaniaz** [comment]
The device is performing a location check of where it and reporting back without permission.

All other devices ask permission before locating user/device.

**Comment by AbuBaniaz** [comment]
Why do you and Ian think that Enigma2 receivers do not need permission to do this?

If there was no issue, all other devices would do the same.

**Comment by Huevos** [comment]
And your point is?

**Comment by Huevos** [comment]
I am nothing to do with this code, so don't bring me into this petty little witch hunt.

**Comment by AbuBaniaz** [comment]
There is no witch hunt.

Ian is quoting you as the validator of this function.

**Comment by Huevos** [comment]
I don't see the word "validator" anywhere (public or private).

I ask Ian to modify the code so it does not touch this database on every reboot. That code is committed.

**Comment by IanSav** [comment]
> As I said no other system does this without user permission.

> We are not talking about what websites do. We are talking about location function.

> The device is performing a location check of where it and reporting back without permission.

> All other devices ask permission before locating user/device.

Really?  It is about time you started backing up your claims.  Prove any of these statements!

**Comment by AbuBaniaz** [comment]
What did fat Tony's post show? His co-ordinates are there albeit incorrect.

You already stated that there is no way to have an option in the GUI at the moment. So the user does not consent to the location check.
 
As requested, BBC website and screwfix
![Location](https://user-images.githubusercontent.com/6644489/82512582-713ba780-9b08-11ea-8aa9-573a749598b8.PNG)

![Location 2](https://user-images.githubusercontent.com/6644489/82512621-86b0d180-9b08-11ea-8c2c-ecca736faf1f.PNG)

**Comment by IanSav** [comment]
That is a third party permission.  Where is the permission form that geolocated your request to get to that website?  A geolocation *did* happen!

**Comment by AbuBaniaz** [comment]
Did that website send information back with my co-ordintes to my device?

**Comment by AbuBaniaz** [comment]
Why don't you start a thread on public forum with a poll for those who want this function. If majority of people agree to have it, let's leave it in.

**Comment by IanSav** [comment]
> Did that website send information back with my co-ordintes to my device?

I can't tell you exactly what it did because the source code is not available to me.  I can guess that it probably logged all your geolocation data and all your browser data.  It would also have captured all the links you used within that website.  If it uses Google Analytics it also sent your data to Google.  Is also probably read some cookies should they be on your machine.  All in all a lot more information is stored and used than what happens on the Enigma2 geolocation lookup.

**Comment by IanSav** [comment]
> Why don't you start a thread on public forum with a poll for those who want this function. If majority of people agree to have it, let's leave it in.

Stef has specifically asked us to *not* discuss this in public.

**Comment by Huevos** [comment]
> 
> 
> Why don't you start a thread on public forum with a poll for those who want this function. If majority of people agree to have it, let's leave it in.

Since when have we done that?

**Comment by tjuerges** [comment]
I do not understand what is to discuss here.  The European Union's General Data Protection Regulation (GDPR) is quite clear about the automated processing of personal data (https://gdpr.eu/).

The European GDPR, article 4 (https://gdpr.eu/article-4-definitions/), defines personal data to be not exclusively but also location data.  The same article defines what the GDPR considers to be the processing of personal data.

Article 2, section 1 declares the European GDPR is applicable as soon as automated processing of personal data is performed:
> This Regulation applies to the processing of personal data wholly or partly by automated means and to the processing other than by automated means of personal data which form part of a filing system or are intended to form part of a filing system.
 
Article 2, section 2.c. makes an exemption:
> 2. This Regulation does not apply to the processing of personal data:
> [...]
> c. by a natural person in the course of a purely personal or household activity;

This exemption does not apply due to the nature of the processing which is computerised and automatic (automatic transmission of data to a service, service performs database query on the data, service returns information) and not by a natural person.  Recital 18 clarifies again that the processing must be performed by a natural person (https://gdpr.eu/Recital-18-Not-applicable-to-personal-or-household-activities/) and therefore machine based processing falls under the European GDPR.

Article 6 GDPR (https://gdpr.eu/article-6-how-to-process-personal-data-legally) defines when consent is required (1.a.) and when not (1.b. - 1.f.):
> 1. Processing shall be lawful only if and to the extent that at least one of the following applies:
>    a. the data subject has given consent to the processing of his or her personal data for one or more specific purposes;
>    b. processing is necessary for the performance of a contract to which the data subject is party or in order to take steps at the request of the data subject prior to entering into a contract;
>    c. processing is necessary for compliance with a legal obligation to which the controller is subject;
>    d. processing is necessary in order to protect the vital interests of the data subject or of another natural person;
>    e. processing is necessary for the performance of a task carried out in the public interest or in the exercise of official authority vested in the controller;
>    f. processing is necessary for the purposes of the legitimate interests pursued by the controller or by a third party, except where such interests are overridden by the interests or fundamental rights and freedoms of the data subject which require protection of personal data, in particular where the data subject is a child.

It is clear that cases 1.b.-1.f. do not apply and therefore case 1.a. is applicable.

The European GDPR Recital 26, notes 5 and 6 (https://gdpr.eu/Recital-26-Not-applicable-to-anonymous-data/), say that
> 5 The principles of data protection should therefore not apply to anonymous information, namely information which does not relate to an identified or identifiable natural person or to personal data rendered anonymous in such a manner that the data subject is not or no longer identifiable.
> 6 This Regulation does not therefore concern the processing of such anonymous information, including for statistical or research purposes.

IP addresses can be traced back to identifiable natural persons and are therefore not to be considered anonymous data.

The software in this repository does not explicitly ask for consent of the data subject and is therefore in violation of the European GDPR.

**Comment by Huevos** [comment]
The software in this repo does not process personal data.

**Comment by tjuerges** [comment]
> The software in this repo does not process personal data. Nor does it have access to it.

If the software performs local processing or not is irrelevant.  The software is sending out personal data without explicit user consent and is therefore in violation of the European GDPR.

**Comment by SimonCapewell** [comment]
Can you explain how you can personally identify me from my PVR's IP address over the other members of my household from a device that holds no personal information and does not log who is using the device at any point in time?

**Comment by tjuerges** [comment]
You cannot discuss the violation away, the GDPR makes not difference if it is you or not.  Feel free to read it yourself.

I tried to help by pointing out the relevant parts in the European GDPR.  You choose to play the ignorance card, your choice.

**Comment by RobvanderDoes** [comment]
The GDPR is very complicated. Many qualified people are not able to read/explain it unequivocally: are you? We're certainly not.

**Comment by SimonCapewell** [comment]
@tjuerges Why the defensiveness? It's a genuine question. You posted a very comprehensive assessment of GDPR and I thought you might be able to explain what makes an IP address personal information.

**Comment by IanSav** [comment]
Before this blows up into another nightmare for anyone / everyone let me just inform you all that the time setting code and geolocation library have been completely rewritten.  Geolocation will now only be done if the user specifically requests it.  Only that data required to set the time zone will be requested.  I promised that I would address the original concerns and I said that a lot of Enigma2 infrastructure would need to change to allow this to happen.  Some of those changes have already happened and some are happening right now (code is under test on an Experimental image).  When that code goes in I hope to be able to ship the new time setting code and the new geolocation code.  Here is an example of the new UI:

![NewTime](https://user-images.githubusercontent.com/6904736/87348007-67c63d00-c597-11ea-98b1-501e5e781c55.jpg)

**Comment by SimonCapewell** [comment]
Thanks Ian. This is the pragmatic approach to the situation and one that'll render the arguments over what legal clauses apply irrelevant.

**Comment by AbuBaniaz** [comment]
The geolocation code in Vix now runs after flashing an image, albeit without user choice and requests only following fields.
```
Data returned:
Status:
Continent:
ContinentCode:
Country:
CountryCode:
Region:
RegionName:
Timezone:
Proxy:
```

Thankfully, the IP address and location among other items are no longer requested.

PLI now requests only
```
status,
message,
timezone,
proxy
```

**Comment by IanSav** [comment]
@tjuerges, I am not sure I understand how GDPR applies in this case.  The user's box is requesting public information about itself.  The user's box is the only recipient of the information.  That information is not stored or sent anywhere other than to the user's device.  Further, there is no processing or fixed decision making being made from the information obtained.  This is not like using the geolocation information on a website to change or control what the user may see or be able to access.  I suspect that this is the user protection to which the GDPR is intended.  The information in this case simply initialises a starting value of the user's current time zone.  The information is shown to the user and the user is able to correct or change the selection as they please.  Absolutely no identifying data is sent as part of the request for information and all the information returned is based on publicly available information.

@Everyone, as I said at the very beginning of this code change, the way the code worked was done because that was all that could reasonably be done in the current Enigma2 structure.  I had to balance uniformity, functionality and performance.  At the time I promised the more reasonable objectors that I would change the code to add user consent when I could restructure Enigma2 enough to allow it.  Those objectors accepted my promise and all was well.  I have been working diligently ever since to address the Enigma2 limitations.

A few months later there was a campaign of lobbying and bullying to have changes made even though the objections were based on misunderstandings rather than fact.  The campaign was run by a few very vocal objectors, in fact I think there was only one, and that forced some images to change the code to silence the furore being raised.  Those changes were different on different images and created a non optimal solution for unifying the Enigma2 code base.

Move forward and I think I have now made sufficient changes to Enigma2 to allow the solution displayed above to become a reality.  This was always my end point and would have happened without all the lobbying and bullying.  It was part of my initial promise and, in spite of all the people who claimed it was a hollow promise, it was my intention to always deliver.

I hope that it is understood that personal nor identifying data was ever exchanged.  Work on Enigma2 has now progressed to a point where I believe that a more globally acceptable mechanism is now approaching production ready code.

Should it be required, I am happy to discuss this matter further but only in the terms of polite and productive discussions.

**Comment by IanSav** [comment]
The new Setup, Time and Geolocation code has now be submitted to the OpenViX Dev branch for testing by the OpenViX developer community.

**Comment by IanSav** [comment]
Sorry, the new time code did not make it into 5.4.000.005 (Developer).  I expect it will appear in 5.4.000.006 (Developer).

**Comment by IanSav** [comment]
My apologies.  The new time setting code is active in the 5.4.000.005 (Developer) build.

I hope people will try it out and check that the change addresses all their concerns.
