### ISSUE TITLE
Subtitles do not show at live tv, but do show when watching recording

### ISSUE THREAD

**Issue by jarmomak** [OpenViX/enigma2#859]
I have configured finnish language (suomi) as a subtitle language. It is ok when watching a recorded program. But live tv subtitles do not work unless I specifically rechoose it (remote's subtitle key). List that appears shows me multiple subtitle codes.
For example YLE TV 1 HD-channel lists:

467  DVB Suomi      (Finnish)
468  DVB Ruotsi      (Swedish)
47e  DVB Suomi      
333  Teletext
455  Teletext
467  DVB                    << OpenVIX marks this last one as selected. Same id is listed twice !!

I change selected subtitle to "467 DVB Suomi", subtitles appear correctly. 
But I have to do this every time I open the box or change the channel.

My device is VU Uno 4k SE. It has a DVB-C tuner.
This bug did not appear at the OpenVIX 5.x series.

**Comment by TwolDE2** [comment]
You need to open a thread on www.world-of-satellite.com (for OpenViX issues), so that we can discuss your problem - here is not the correct place.
5.4 was 2 years ago, so there may be issues between python 3 and the C++ code or a commit to the C++ code....whatever, it needs tests and a look at your settings for audio/sub titles.
